upkeep: update `render-readme.yml`
Closes #258

diff --git a/.github/workflows/render-readme.yml b/.github/workflows/render-readme.yml
--- a/.github/workflows/render-readme.yml
+++ b/.github/workflows/render-readme.yml
@@ -1,35 +1,38 @@
+# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
+# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
 on:
   push:
-    branches: [main, master]
-  pull_request:
-    branches: [main, master]
+    paths: ['README.Rmd']
 
-name: Render README
+name: render-readme
 
 jobs:
-  render:
-    name: Render README
-    runs-on: ubuntu-latest
-    timeout-minutes: 10
+  render-readme:
+    runs-on: macos-latest
     env:
       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
     steps:
-      - uses: actions/checkout@v4
-      - uses: r-lib/actions/setup-r@v2
+      - name: Checkout repo
+        uses: actions/checkout@v4
         with:
-          use-public-rspm: true
+          fetch-depth: 0
+
       - uses: r-lib/actions/setup-pandoc@v2
-      - name: Install rmarkdown, remotes, and the local package
+
+      - uses: r-lib/actions/setup-r@v2
+
+      - uses: r-lib/actions/setup-r-dependencies@v2
+
+      - name: Install the local package
         run: |
-          install.packages("remotes")
-          remotes::install_local(".")
-          remotes::install_cran("rmarkdown")
-        shell: Rscript {0}
-      - name: Render README
-        run: Rscript -e 'rmarkdown::render("README.Rmd")'
-      - name: Commit results
+          Rscript -e 'install.packages("remotes")'
+          Rscript -e 'remotes::install_local(".")'
+
+      - name: Render README.Rmd file and Commit Results
         run: |
-          git config --local user.email "actions@github.com"
-          git config --local user.name "GitHub Actions"
-          git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
+          README_PATH=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'README.Rmd$'))
+          Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) rmarkdown::render(f)' ${README_PATH[*]}
+          git config --local user.name "$GITHUB_ACTOR"
+          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
+          git commit ${README_PATH[*]/.Rmd/.md} -m 'Re-build Rmarkdown files' || echo "No changes to commit"
           git push origin || echo "No changes to commit"
